<!DOCTYPE html>
<html>
<head>
   <link rel="stylesheet" type="text/css" href="../dist/design.css"/>
    <title>Load Documents in Browser using PHPSpreadsheet and PHPWord</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
<!--    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="index.js"></script>
</head>
<body>

<div class="flexbox-container">
    <div class="header"><h2 style="text-align: center;">UniWord</h2></div>

  <div class = "middle">
  	  	<div class="MP">
            <div class='div1 divs'>
                <h1>Insert Student</h1>
                <div>
                    <form  class = "aligned_form" method="post" id="add_student_form">
                        <label for = 'a' >First Name : </label>
                        <input type="text" name="first_name"><br>
                        <label for = 'b' >Email : </label>
                        <input type="text" name="email"><br>
                        <label for = 'c' l>Street : </label>
                        <input type="text" name="street"><br>
                        <label>City : </label>
                        <input type="text" name="city"><br>
                        <label>State : </label>
                        <input type="text" name="state"><br>
                        <label>Zip Code : </label>
                        <input type="text" name="zip"><br>
                        <label>Phone : </label>
                        <input type="text" name="phone"><br>
                        <label>Birth Date : </label>
                        <input type="text" name="birthdate"><br>
                        <label>Sex : </label>
                        <input type="text" name="sex"><br>
                        <label>Lunch Cost : </label>
                        <input type="text" name="lunch"><br>
                        <input method = "post" name="Add" type="submit" value="Add Student"  class="btn-primary" ><br>
                    </form>


                    <br />
                </div>
                </div>
            <div  class='div2 divs'><h1 align="Left">Upload files</h1>
                <div>
                    <div class="table-responsive">
                        <!-- Excel Form Loading Data -->
                        <span id="message"></span>
                        <form method="POST" id="load_excel_form" enctype="multipart/form-data">
                            <table class="table">
                                <tr>
                                    <td width="25%" align="right">Select File</td>
                                    <td width="50%"><input type="file" id ="filename" name="filename" /></td>
                                    <td  ><input type="submit" name="load" id="btn"   class="btn-primary" /></td>
                                </tr>
                            </table>
                        </form>
                    </div>
                    <div id="excel_area"></div>
                </div>
            </div>
            <div class='div3 divs'>
                <h1>Download Student details</h1>
                <a name="a_download" method = "GET" id ="download" href="/Uniword/web/router.php">Download</a>

            </div>

        </div>
  	  	<div class="LP">
      <div class='leftNav'>

              <a  href='#' class='b1 buttons' data-target='.div1'  >Insert Student</a>

         </br> </br>
          <a  href='#' class='b2 buttons' data-target='.div2'>Upload Files</a>
          </br> </br>
          <a href='#' class='b3 buttons' data-target='.div3'>Download Student Details</a>
          </br> </br>

          </div>
        </div>
      <div class = "RP"></div>

  	
  </div>
  <div class = "footer">


                          <h3 style="color: black;">Stay in touch</h3>
                          <h1 style="color: black;">Ankit Vig</h1>

                              <a  style="color: black;" href="mailto:ankitkumarvig@gmail.com" class="contact-link">ankitkumarvig@gmail.com</a>


                              <div >
                                  <ul>

                                      <li><a style="color: black;" href="https://github.com/AnkitVig" target="_blank">GitHub</a></li>
                                      <li><a style="color: black;" href="https://www.linkedin.com/in/ankitkumarvig/" target="_blank" style="color: #0e76a8">LinkedIn</a></li>

                                  </ul>
                              </div>

                      </div>



</body>
</html>